### ISSUE TITLE
上拉触底，发现只触发一次

### ISSUE THREAD

**Issue by weizuichunsun** [x3852/miniprogram-dropload#1]
上拉触底，无法触发，scroll-view 高度未设置有关吗？

**Comment by qiuwenxing** [comment]
组件内部scroll-view高度是100%的，所以组件父元素高度一般为页面百分比固定高度
![image](https://user-images.githubusercontent.com/26081477/49632276-13a8bd80-fa30-11e8-9177-0b1ece8de0bc.png)
