### ISSUE TITLE
	loadData里的reset什么意思啊》

### ISSUE THREAD

**Issue by gaoran5975** [x3852/miniprogram-dropload#6]
loadData:function(reset = false) {
let that = this;
       return  new Promise(function(resolve, reject) {
       wx.request({
            url: '‘’',
            method: 'GET',
            data: {
            },
            success(res) {

              })
            }
          });  
}

只执行了一次，请问还需要设置哪里吗？

**Comment by qiuwenxing** [comment]
reset用于区分是翻页还是重新加载，reset=true就是重新加载，否则就是加载下一页的数据

**Comment by gaoran5975** [comment]
收到了，谢谢你。
